server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:
      host: 172.16.246.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}